### ISSUE TITLE
Report Format

### ISSUE THREAD

**Issue by Aaly1987** [Apoc70/Get-ExchangeEnvironmentReport#6]
Dear, 

when i run this report on Exchange server 2019 that running on OS 2019, the Html report come without any formatting no tables no colors and so on 

waiting your feedback

**Comment by Apoc70** [comment]
I am not aware of any issues with Windows Server 2019. Do you run the script with elevated permissions?
What is the exact parameter set you use, when running the script?

**Comment by zjwww** [comment]
same issue on Windows Server 2016 & Exchange Server 2016, already run in elevated powershell.

**Comment by n4bs** [comment]
+1 with same issue

parameter:  -HTMReport ExchangeEnvironment.html -SendMail  -MailFrom:11111 -MailTo:"111111" -MailServer:111111

![image](https://user-images.githubusercontent.com/49108103/120824113-68254900-c558-11eb-8968-4207e9c12bf0.png)

**Comment by Apoc70** [comment]
It seems as if the .css file, containing all the required Html styles is missing. Did you download the CSS file? And is it accessible in the same folder?

**Comment by Apoc70** [comment]
The formatting is based on the CSS file EnvironmentReport.css. Is this file accessible in the same folder?

It seems that I need to add debug outputs, as I cannot reproduce that issue in any of the client environments that I run the script in. Did any of you run Set-ADServerSetting -viewentireforest:true before running the script?

**Comment by Jaturongg** [comment]
> The formatting is based on the CSS file EnvironmentReport.css. Is this file accessible in the same folder?
> 
> It seems that I need to add debug outputs, as I cannot reproduce that issue in any of the client environments that I run the script in. Did any of you run Set-ADServerSetting -viewentireforest:true before running the script?

Your solution was worked.

**Comment by andypituch** [comment]
@Apoc70 - Would it be possible to add a check to the script to see if the CSS file is present in the current directory and displaying a warning or an error if it's not. The docs (MD on GitHub or the description within the script) do not mention the CSS file dependency and adding a check would prevent this "issue" from being reported/experienced.
