### ISSUE TITLE
Run script

### ISSUE THREAD

**Issue by pepsolutionsghana** [Apoc70/Get-ExchangeEnvironmentReport#7]
I get error when i try to run the script on Windows Server 2019 -Exchange Server 2019 Management shell.
Please assist on how to run this script.
Image attach
![WhatsApp Image 2021-04-13 at 23 09 03](https://user-images.githubusercontent.com/82499747/114672495-bb1b1680-9cf4-11eb-80da-70c127c6e28d.jpeg)

**Comment by Apoc70** [comment]
Did you download the script or did you use copy and paste to copy the content to a new PowerShell-Script file?
It seems that the quotation marks are wrong, which is not the case in the original file.

**Comment by pepsolutionsghana** [comment]
I did download.. Can i get the original file via email ... pepsolutionsghana@gmail.com

**Comment by Apoc70** [comment]
@pepsolutionsghana 
I tested the version from this repository on an Exchange Server 2019 with CU20 installed. I did not encounter any issues.
At this point, I am not aware of any PowerShell culture-setting-related issues. 
Can you please post the PowerShell culture settings that you use in your PowerShell session?
Execute the cmdlet Get-Culture to get the settings of the current PowerShell session.

**Comment by pepsolutionsghana** [comment]
1033             en-US            English (United States)

this is what i have from Get-Culture

**Comment by Apoc70** [comment]
I need to set up such a system to test.

**Comment by jonadreid** [comment]
I realized what is happening. Stupid but obvious solution!  When right-clicking on the file and choosing "save link as" and downloading the Get-ExchangeEnvironmentReport.ps1, it doesn't download your script, but creates a .ps1 file with that name and instead adds all of the HTML from that github site to the ps1 file. Instead you need to go to the file itself and then from the top right menu of the  script contents choose the icon which reads "Copy raw contents". Then just paste that into a .ps1 file and save it.

Nothing wrong with the script at all! doh!

![notascript](https://user-images.githubusercontent.com/53827000/139700162-1d8863fe-3f79-4893-b594-929cef912524.png)

**Comment by Apoc70** [comment]
Thanks for your feedback.
