### ISSUE TITLE
Exception calling "Join" with "2" argument(s): "Value cannot be null.

### ISSUE THREAD

**Issue by alef-adm** [Apoc70/Get-ExchangeEnvironmentReport#9]
The script crashed with error. Help please!

Exception calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"
At C:\1\Get-ExchangeEnvironmentReport-master\Get-ExchangeEnvironmentReport.ps1:743 char:5
+     $ExtNames = [string]::Join(',',$ExtNames)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

**Comment by alef-adm** [comment]
Exchange 2016 CU22 + KB5007012

**Comment by TheCaverDave** [comment]
Seeing the same error... any traction on resolution?

**Comment by alef-adm** [comment]
> Seeing the same error... any traction on resolution?

while not :(

**Comment by TheCaverDave** [comment]
> Can you share some more information about the environment where you run the script? From a remote computer? On an Exchange Server?

Exchange 2016 CU22... script is run ON/from one of the 9 servers

**Comment by alef-adm** [comment]
> @alef-adm Can you share some more information about the environment where you run the script? From a remote computer? On an Exchange Server?

script runs from Exchange server

**Comment by GonpE** [comment]
Hi, i have this exact error in a new Windows Server 2019 with Exchange 2019. The server are new with just 2 account if helps.
I run the script from the same server.

**Comment by Apoc70** [comment]
@GonpE As ExtNames contains the ExternalUrl host names from any virtual directory, can you please check whether your Exchange servers have virtual directories without an ExternalUrl set?

**Comment by Apoc70** [comment]
I will push a new version by tomorrow.
